# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
cask "peasant" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "197ad9fc4df7ec3232ee773a3fdc4773b2ce152454671ebebac0112ee31a70d1"
      url "https://github.com/peasant-labs/peasant/releases/download/v#{version}/peasant_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "84d9a8f2b474292d5ff72c736d88b13a0f40baaf3108d50180329e076d220808"
      url "https://github.com/peasant-labs/peasant/releases/download/v#{version}/peasant_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d6be33dd96b459c5c8d1df5725fa238b9244ff7c4c9e46237b7da147940ae49f"
      url "https://github.com/peasant-labs/peasant/releases/download/v#{version}/peasant_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "48236c32ff4c47917b4ea0b64eafd9853c950fb57a346bf5da52c5d24576fc6b"
      url "https://github.com/peasant-labs/peasant/releases/download/v#{version}/peasant_#{version}_linux_amd64.tar.gz"
    end
  end

  name "peasant"
  desc "Agent-session ingest, analytics, and publishing CLI"
  homepage "https://github.com/peasant-labs/peasant"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "peasant"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "peasant"], chdir: "."
    end
  end

  # No zap stanza required
end
