# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
cask "peasant" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "a25e68b2123b25121f18937b7a6012b0560d909115950f456103d5c0525ab18c"
      url "https://github.com/peasant-labs/peasant/releases/download/v#{version}/peasant_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5341f535c909ce0b32b67e8f952eac9460907dd549f20645df71d51fb7889486"
      url "https://github.com/peasant-labs/peasant/releases/download/v#{version}/peasant_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f14f13e4f07b694ba14214b0b4659a7e6b4ee3a6c4ac2e90127d87477f3e7bab"
      url "https://github.com/peasant-labs/peasant/releases/download/v#{version}/peasant_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "383fe922b0d48f5b8587c5365c7f511ee4d3bdee272e8b73717ff391fb59a22d"
      url "https://github.com/peasant-labs/peasant/releases/download/v#{version}/peasant_#{version}_linux_amd64.tar.gz"
    end
  end

  name "peasant"
  desc "Agent-session ingest, analytics, and publishing CLI"
  homepage "https://github.com/peasant-labs/peasant"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "peasant"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "peasant"], chdir: "."
    end
  end

  # No zap stanza required
end
