# This file was generated by GoReleaser. DO NOT EDIT.
cask "peasant" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "48ea38d73bb263335165353a20b1b9ab897570341ac4c34e9ef96f7ee713b99f"
      url "https://github.com/peasant-labs/peasant/releases/download/v#{version}/peasant_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f2202f2ccab3880583f945f7e7bc5eba01f8ffaf069d92ccf17f4f2b643ff98e"
      url "https://github.com/peasant-labs/peasant/releases/download/v#{version}/peasant_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8cee54f84aefb2491073aea30380dc48368ca3e52f649b501eaa4e1fb00ca3e5"
      url "https://github.com/peasant-labs/peasant/releases/download/v#{version}/peasant_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "452f10e420c1664274184ada58b7af070a7d257a6023326c776ac21f1fbc180c"
      url "https://github.com/peasant-labs/peasant/releases/download/v#{version}/peasant_#{version}_linux_amd64.tar.gz"
    end
  end

  name "peasant"
  desc "Agent-session ingest, analytics, and publishing CLI"
  homepage "https://github.com/peasant-labs/peasant"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "peasant"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "peasant"], chdir: "."
    end
  end

  # No zap stanza required
end
