# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
cask "probe-real" do
  version "0.0.0-SNAPSHOT-none"

  on_macos do
    on_arm do
      sha256 "3f7dbf89a46541dabd9271705d9cfd3f18827c31f393f853e13ba22d52ef73b4"
      url "https://github.com///releases/download/v0.0.0/peasant_#{version}_darwin_arm64"
      binary "peasant_0.0.0-SNAPSHOT-none_darwin_arm64", target: "peasant"
    end
  end

  name "probe-real"
  desc "Agent-session ingest, analytics, and publishing CLI"
  homepage "https://github.com/peasant-labs/peasant"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required
end
